---
title: "Best practice guide for Bristol Uni users of OpenSAFELY"
author:
  - Tom Palmer
  - Elsie Horne
  - Venexia Walker
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    # toc: true
    # toc_float:
    #   collapsed: false
    #   smooth_scroll: false
    # toc_depth: 2
    # code_download: true
    # code_folding: show
    anchor_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction 

The following is intended as a set of tips for Bristol Uni users of the OpenSAFELY system.

## Best practice guide{.tabset .tabset-pills .tabset-fade} 

### `project.yaml`

### `study_definition.py`

#### Dummy data
- To ensure the dummy data system generates exactly the same data everytime you run it, set a random number generator seed at the top of this file with

    ``` python
    import numpy as np
    np.random.seed(123456)
    ```

#### Dataset formats
- Please use feather for highly_sensitive output for inputting into your R scripts  

    ``` yaml
    generate_study_population_vax:
      run: cohortextractor:latest generate_cohort --study-definition study_definition_vax --output-format feather
     needs: 
      - design
      outputs:
        highly_sensitive:
          cohort: output/input_vax.feather
    ```  
  - Use the **arrow** package read the `.feather` file into R
  - Then have an initial processing R script which formats the `.feather` file, which you `source('')` at the start of your R analysis scripts  
  - Or e.g., `01_processing.R` which outputs to `.rds` or `.Rdata` format; 
  - Use `readr::read_rds()` to read this into R
  
<!--
  - Alternatively, use the **vroom** package, the `vroom::vroom()` function has the `col_sel` argument
-->

  - Please use `.csv` for moderately_sensitive output

### Redacting output

- Will's redaction functions

### R code


### Jupyter and Rmd notebooks

- If you use a Jupyter notebook create a folder called `notebooks` at the top level of your repo
  - Only use Python code chunks within the notebook
  - The action to compile the notebook will be of the form

    ``` yaml
      generate_notebook:
        run: jupyter:latest jupyter nbconvert /workspace/analysis/report.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
        needs:
        outputs:
          moderately_sensitive:
            notebook: output/report.html
    ```

- If you use an R Markdown notebook within your repo create a folder called `rmarkdown` at the top level of the repo
  - In the YAML header of the .Rmd file define the output type as `output: html_document`
  - Write a separate .R script that runs a single command 
  
    ``` r
    rmarkdown::render('myrmdfile.Rmd', encoding = 'UTF-8') 
    ```  
  - And write an `r` action to run the script which will produce the .html output file
